/*
 * Copyright (c) @CompanyNameMagicTag 2018-2019. All rights reserved.
 * Description: SOCAUDIO USER EVENT LOG MODULE INTERFACE
 */
#ifndef SOCAUDIO_USER_EVENT_LOG_H
#define SOCAUDIO_USER_EVENT_LOG_H

/**
 * @addtogroup connectivity_drivers_non_os_log
 * @{
 */
/* user defined */
#define EVENT_FILL_NO_RESULT   0
#define EVENT_EVENT_VERSION    ""

typedef enum {
    EVENT_COMMON_SUCCESS = 0x00,
    EVENT_COMMON_FAIL = 0x01,
    EVENT_RESULT_END
} event_common_result_t;

/* first-level:EventID */
typedef enum {
    EVENT_WEAR_MANAGER = 0x00,
    EVENT_BT_SEVICE_MANAGER = 0x01,
    EVENT_BTC_MANAGER = 0x03,
    EVENT_WRIST_MANAGER = 0x04,
    EVENT_POWER_MANAGER = 0x06,
    EVENT_HARDWARE_MANAGER = 0x07,
    EVENT_WS_CALL_MANAGER = 0x0A,
    EVENT_MUSIC_MANAGER = 0x0C,
    EVENT_UPGRADE = 0x10,
    EVENT_LOG_MANAGER = 0x12,
    EVENT_BOX_MANAGER = 0x13,
    EVENT_AUDIO_MANAGER = 0x14,
    EVENT_POWER = 0x15,
    EVENT_MODULE_END
} log_event_module_t;

/* second-level:Info1 */
typedef enum {
    EVENT_SINGLE_WEAR = 0x12,
    EVENT_WEAR_DAILY_STATISTICS = 0x13,
} event_wear_manager_info1_t;

typedef enum {
    EVENT_BT_DEVICE_MANAGER = 0x01,
    EVENT_BT_WORK_MODE = 0x02,
    EVENT_BT_UX_EVT = 0x03,
    EVENT_BT_DEVICE_TYPE = 0x04,
    EVENT_BT_NV_MANAGER = 0x05,
    EVENT_BT_UX_BOX_EVT = 0x06,
    EVENT_BT_UX_WEAR_EVT = 0x07,
    EVENT_BT_UX_EARBUDS_CUSTOM_EVT = 0x08,
    EVENT_BT_UX_VOLUME_EVT = 0x09,
    EVENT_BT_UM_CONNECT = 0x20,
    EVENT_BT_UM_DEVICE_DETAIL = 0x21,
    EVENT_BT_UM_UNICAST = 0x22,
    EVENT_BT_UM_CODEC = 0x23,
    EVENT_BT_UM_VOLUME = 0x24,
    EVENT_BT_UM_APP_OPERATION = 0x25,
    EVENT_BT_UM_VAD = 0x26,
    EVENT_BT_UM_DATATRANS = 0x27,
    EVENT_BT_UM_LOCATION = 0x28,
    EVENT_BT_UM_BROADCAST = 0x29,
    EVENT_BT_KPI_CONNECT = 0x30,
    EVENT_BT_KPI_HANDOVER = 0x31,
    EVENT_BT_KPI_PROFILE = 0x32,
    EVENT_BT_KQI_TRANSPORT = 0x33,
    EVENT_BT_KQI_AUDIO_QUALITY = 0x34,
    EVENT_BT_KQI_HD = 0x35,
    EVENT_BT_REMOTE_DEVICE_INFO = 0x36,
    EVENT_BT_SEVICE_MANAGER_INFO1_END
} event_bt_sevice_manager_info1_t;

typedef enum {
    EVENT_BT_CALI = 0x01,
    EVENT_BTC_TEMP_RSSI_INFO = 0x02,
    EVENT_BTC_ERROR = 0x03,
    EVENT_BTC_ERROR_CASE = 0x04,
    EVENT_BTC_MANAGER_INFO1_END
} event_btc_manager_info1_t;

typedef enum {
    EVENT_WEAR_TAKE_ON = 0x00,
    EVENT_WEAR_TAKE_OFF = 0x01,
    EVENT_WRIST_MANAGER_INFO1_END
} event_wrist_manager_info1_t;

typedef enum {
    EVENT_POWER_ON = 0x01,
    EVENT_POWER_OFF = 0x02,
    EVENT_BATTERY_ID = 0x03,
    EVENT_MANAGER__INBOX_POWER = 0x04,
    EVENT_MANAGER__OUTBOX_POWER = 0x05,
    EVENT_WEAR_TAKE_ON_CAPACITY = 0x0A,
    EVENT_WEAR_TAKE_OFF_CAPACITY = 0x0B,
    EVENT_MANAGER_CALL_POWER = 0x0C,
    EVENT_MANAGER_MUSIC_POWER = 0x0E,
    EVENT_MANAGER__HANDOVER_POWER = 0x14,
    EVENT_MANAGER__GESTURE_POWER = 0x16,
    EVENT_POWER_LOW_ALERT = 0x22,
    EVENT_BATTERY_CHANGE = 0x23,
    EVENT_TEMP_PROTECT_MANAGER = 0x25,
    EVENT_POWERON_TIMING = 0x28,
    EVENT_CHARGING_STATISTIC = 0x29,
    EVENT_POWER_ULPM = 0x30,
    EVENT_POWER_STATISTICS = 0x31,
    EVENT_BAT_CV_POINT = 0x32,
    EVENT_BAT_CALI_DONE = 0x33,
    EVENT_WORKING_HOURS_WHEN_CHARGE = 0x34,
    EVENT_POWER_MANAGER_INFO1_END
} event_power_manager_info1_t;

typedef enum {
    EVENT_PRESS_KEY_MANAGER = 0x01,
    EVENT_MIC_MANAGER = 0x02,
    EVENT_SPK_MANAGER = 0x04,
    EVENT_SENSOR_MANAGER = 0x0B,
    EVENT_CODEC_MANAGER = 0x11,
    EVENT_DSP_MANAGER = 0x12,
    EVENT_HARDWARE_MANAGER_INFO1_END
} event_hardware_manager_info1_t;

typedef enum {
    EVENT_WS_CALL_INCOMING = 0x01,
    EVENT_WS_CALL_ANSWER = 0x02,
    EVENT_WS_CALL_DIAL = 0x03,
    EVENT_WS_CALL_END = 0x04,
    EVENT_WS_CALL_MANAGER_INFO1_END
} event_ws_call_manager_info1_t;

typedef enum {
    EVENT_MUSIC_MANAGER_VOICE_REGULATION = 0x03,
    EVENT_MUSIC_MANAGER_CONTROL = 0x04,
    EVENT_MUSIC_MANAGER_INFO1_END
} event_music_manager_info1_t;

typedef enum {
    EVENT_UPGRADE_START = 0x01,
    EVENT_UPGRADE_TYPE = 0x02,
    EVENT_UPGRADE_FAIL = 0x03,
    EVENT_UPGRADE_END = 0x04,
    EVENT_UPGRADE_TRANS = 0x05,
    EVENT_UPGRADE_CONFIRM = 0x06,
    EVENT_UPGRADE_VERSION = 0x07,
    EVENT_UPGRADE_VERSION_CURRENT = 0x08,
    EVENT_UPGRADE_INFO1_END
} event_upgrade_info1_t;

typedef enum {
    EVENT_LOG_MCU_BT_CONTENT_RECORD_FULL = 0x02,
    EVENT_LOG_NOTIFY_APP_FETCH_CONTENT = 0x03,
    EVENT_LOG_UPDATE_TRANS = 0x04,
    EVENT_LOG_MEMORY_POOL_MAX_USED_VALUE_MONITOR = 0x05,
    EVENT_LOG_MANAGER_INFO1_END
} event_log_manager_info1_t;

typedef enum {
    EVENT_BOX_OPEN_CLOSE = 0x01,
    EVENT_BOX_TWS_IN_OUT = 0x02,
    EVENT_BOX_KEY = 0x03,
    EVENT_BOX_CHARGE_MANAGER = 0x04,
    EVENT_BOX_CHARGER_MANAGER = 0x05,
    EVENT_BOX_MANAGER_INFO1_END
} event_box_manager_info1_t;

typedef enum {
    EVENT_AUDIO_ANC_MANAGER = 0x01,
    EVENT_AUDIO_HT_MANAGER = 0x02,
    EVENT_AUDIO_VOICE_WAKEUP_MANAGER = 0x03,
    EVENT_AUDIO_VOICE_ID = 0x04,
    EVENT_AUDIO_MANAGER_INFO1_END
} event_audio_manager_info1_t;

typedef enum {
    EVENT_POWER_BASE_SOC = 0x01,
    EVENT_POWER_BASE_FCC = 0x02,
    EVENT_POWER_BASE_VOLTAGE = 0x03,
    EVENT_POWER_BASE_CURRENT = 0x04,
    EVENT_POWER_BASE_CYCLE = 0x05,
    EVENT_POWER_BASE_SOH = 0x06,
    EVENT_POWER_BASE_TEMPERATURE = 0x07,
    EVENT_POWER_ABNORMAL = 0x11,
    EVENT_POWER_PROTECT_UT = 0x21,
    EVENT_POWER_PROTECT_OT = 0x22,
    EVENT_POWER_PROTECT_OV = 0x23,
    EVENT_POWER_PROTECT_UV = 0x24,
    EVENT_POWER_PROTECT_OCC = 0x25,
    EVENT_POWER_PROTECT_OCD = 0x26,
    EVENT_POWER_PROTECT_UC = 0x27,
    EVENT_POWER_INFO1_END
} event_power_info1_t;

/* third-level:Info2 */
typedef enum {
    EVENT_WEAR_OUT_TIME = 0x01,
    EVENT_SINGLE_WEAR_OUT_TIME = 0x02,
} event_wear_single_wear_info2_t;

typedef enum {
    EVENT_BT_POWER_ON = 0x01,
    EVENT_BT_POWER_OFF = 0x02,
    EVENT_BT_RESET = 0x03,
    EVENT_BT_CLOSE_BT = 0x04,
    EVENT_BT_DEVICE_MANAGER_INFO2_END
} event_bt_device_manager_info2_t;

typedef enum {
    EVENT_BT_WORK_MODE_TWS = 0x01,
    EVENT_BT_WORK_MODE_SOLO = 0x02,
    EVENT_BT_WORK_MODE_FACTORY = 0x03,
    EVENT_BT_WORK_MODE_INFO2_END
} event_bt_work_mode_info2_t;

typedef enum {
    EVENT_BT_UX_KEYPRESS = 0x01,
    EVENT_BT_UX_NEARBY = 0x02,
    EVENT_BT_UX_CALL = 0x03,
    EVENT_BT_UX_MEDIA = 0x04,
    EVENT_BT_UX_AUDIO = 0x05,
    EVENT_BT_UX_VOICE_CTRL = 0x06,
    EVENT_BT_UX_SERVICE_CTRL = 0x07,
    EVENT_BT_UX_COMMON = 0x08,
    EVENT_BT_UX_EVT_INFO2_END
} event_bt_ux_evt_info2_t;

typedef enum {
    EVENT_BT_TWS_NATURE = 0x01,
    EVENT_BT_TWS_ROLE = 0x02,
    EVENT_BT_DEVICE_TYPE_INFO2_END
} event_bt_device_type_info2_t;

typedef enum {
    EVENT_BT_NV_READ = 0x01,
    EVENT_BT_NV_WRITE = 0x02,
    EVENT_BT_NV_MANAGER_INFO2_END
} event_bt_nv_manager_info2_t;

typedef enum {
    EVENT_BT_UX_BOX = 0x01,
    EVENT_BT_UX_BOX_EVT_INFO2_END
} event_bt_ux_box_evt_info2_t;

typedef enum {
    EVENT_BT_UX_WEAR = 0x01,
    EVENT_BT_UX_WEAR_EVT_INFO2_END
} event_bt_ux_wear_evt_info2_t;

typedef enum {
    EVENT_BT_UX_EARBUDS_CUSTOM = 0x01,
    EVENT_BT_UX_EARBUDS_CUSTOM_EVT_INFO2_END
} event_bt_ux_earbuds_custom_evt_info2_t;

typedef enum {
    EVENT_BT_UX_VOLUME = 0x01,
    EVENT_BT_UX_VOLUME_EVT_INFO2_END
} event_bt_ux_volume_evt_info2_t;

typedef enum {
    EVENT_BT_UM_TWS_MODE = 0x01,
    EVENT_BT_UM_CONNECT_MODE = 0x02,
    EVENT_BT_UM_CONNECT_METHOD = 0x03,
    EVENT_BT_UM_DISCONNECT_TYPE = 0x04,
    EVENT_BT_UM_CONNECT_INFO2_END
} event_bt_um_connect_info2_t;

typedef enum {
    EVENT_BT_UM_CONNECT = 0x01,
    EVENT_BT_UM_CONNECT_ANDROID = 0x02,
    EVENT_BT_UM_CONNECT_IOS = 0x03,
    EVENT_BT_UM_CHIPSET_MANU_ID_HIGH = 0x04,
    EVENT_BT_UM_CHIPSET_MANU_ID_LOW = 0x05,
    EVENT_BT_UM_CHIPSET_VERSION = 0x06,
    EVENT_BT_UM_CHIPSET_SUB_VERSION_HIGH = 0x07,
    EVENT_BT_UM_CHIPSET_SUB_VERSION_LOW = 0x08,
    EVENT_BT_UM_DEVICE_DETAIL_INFO2_END
} event_bt_um_device_detail_info2_t;

typedef enum {
    EVENT_BT_UM_UNICAST_KARAOKE = 0x01,
    EVENT_BT_UM_UNICAST_LIVELISTEN = 0x02,
    EVENT_BT_UM_UNICAST_VOIP = 0x03,
    EVENT_BT_UM_UNICAST_MESSAGE = 0x04,
    EVENT_BT_UM_UNICAST_BASIC = 0x05,
    EVENT_BT_UM_UNICAST_PROFILE = 0x06,
    EVENT_BT_UM_UNICAST_SCENE = 0x07,
    EVENT_BT_UM_UNICAST_INFO2_END
} event_bt_um_unicast_info2_t;

typedef enum {
    EVENT_BT_UM_CODEC_CVSD = 0x01,
    EVENT_BT_UM_CODEC_MSBC = 0x02,
    EVENT_BT_UM_CODEC_SBC = 0x03,
    EVENT_BT_UM_CODEC_AAC = 0x04,
    EVENT_BT_UM_CODEC_HWA = 0x05,
    EVENT_BT_UM_CODEC_HWA_2P0 = 0x06,
    EVENT_BT_UM_CODEC_LC3 = 0x07,
    EVENT_BT_UM_CODEC_L2HC = 0x08,
    EVENT_BT_UM_CODEC_L2HC_LC3 = 0x09,
    EVENT_BT_UM_CODEC_INFO2_END
} event_bt_um_codec_info2_t;

typedef enum {
    EVENT_BT_UM_MEDIA_VOLUME = 0x01,
    EVENT_BT_UM_CALL_VOLUME = 0x02,
    EVENT_BT_UM_ABS_VOL = 0x03,
    EVENT_BT_UM_VOLUME_INFO2_END
} event_bt_um_volume_info2_t;

typedef enum {
    EVENT_BT_UM_APP_WEAR_CHECK_SWITCH = 0x01,
    EVENT_BT_UM_APP_MULTI_CONN_SWITCH = 0x02,
    EVENT_BT_UM_APP_HD_VOICE_SWITCH = 0x03,
    EVENT_BT_UM_APP_OPERATION_INFO2_END
} event_bt_um_app_operation_info2_t;

typedef enum {
    EVENT_BT_UM_VOICE_RECOGNITION = 0x01,
    EVENT_BT_UM_VOICE_IDENTITY = 0x02,
    EVENT_BT_UM_AUTO_SOUND_RECOGNITION = 0x03,
    EVENT_BT_UM_VAD_INFO2_END
} event_bt_um_vad_info2_t;

typedef enum {
    EVENT_BT_UM_MOBILE_SETTINGS = 0x01,
    EVENT_BT_UM_DEVICE_SETTINGS = 0x02,
    EVENT_BT_UM_MOBILE_WEAR_DETECT = 0x03,
    EVENT_BT_UM_DEVICE_WEAR_DETECT = 0x04,
    EVENT_BT_UM_MOBILE_CHR = 0x05,
    EVENT_BT_UM_DEVICE_CHR = 0x06,
    EVENT_BT_UM_MOBILE_FOTA = 0x07,
    EVENT_BT_UM_MOBILE_ICONNECT = 0x08,
    EVENT_BT_UM_MOBILE_VID = 0x09,
    EVENT_BT_UM_MOBILE_DEFAULT_SVR = 0x0A,
    EVENT_BT_UM_MOBILE_CLOUD_SVR = 0x0B,
    EVENT_BT_UM_DATATRANS_INFO2_END
} event_bt_um_datatrans_info2_t;

typedef enum {
    EVENT_BT_KPI_NEARBY = 0x01,
    EVENT_BT_KPI_PAGE_SCAN = 0x02,
    EVENT_BT_KPI_MOBILE_CONNECT = 0x03,
    EVENT_BT_KPI_TWS_CONNECT = 0x04,
    EVENT_BT_KPI_MOBILE_PAIR = 0x05,
    EVENT_BT_KPI_RECONNECT = 0x06,
    EVENT_BT_KPI_OPENBOX_RECONNECT = 0x07,
    EVENT_BT_KPI_TWS_RECONNECT = 0x08,
    EVENT_BT_KPI_MOB_DISCONN_UNDER_RECONN = 0x09,
    EVENT_BT_KPI_MOBILE_DISCONN = 0x0A,
    EVENT_BT_KPI_TWS_DISCONN = 0x0B,
    EVENT_BT_KPI_EAR_ABORT_CONNECTING = 0x0C,
    EVENT_BT_KPI_MOBILE_DISCONN_BTC_ERR_CASE = 0x0D,
    EVENT_BT_KPI_TWS_DISCONN_BTC_ERR_CASE = 0x0E,
    EVENT_BT_KPI_TWS_CONNECT_TIME = 0x0F,
    EVENT_BT_KPI_MOBILE_CONNECT_TIME = 0x10,
    EVENT_BT_KPI_ACTIVE_DISC_REASON = 0x11,
    EVENT_BT_KPI_MOB_DISCON_CONNECTION_PREEMPTION = 0x12,
    EVENT_BT_KPI_HCI_DIE_CMD_OPCODE = 0x13,
    EVENT_BT_KPI_WORK_MODE = 0x14,
    EVENT_BT_KPI_MOBILE_CONNECT_TIME_SOCTWS = 0x15,
    EVENT_BT_KPI_SOCTWS_MOBILE_DISCONN_BTC_ERR_CASE = 0x16,
    EVENT_BT_KPI_SOCTWS_TWS_DISCONN_BTC_ERR_CASE = 0x17,
    EVENT_BT_KPI_CONN_A2DP_REQ = 0x18,
    EVENT_BT_KPI_CONN_SCO_REQ = 0x19,
    EVENT_BT_KPI_CONN_SCO_STATE_CHANGE = 0x1A,
    EVENT_BT_KPI_CONN_NON_IN_BAND_RING = 0x1B,
    EVENT_BT_KPI_CONN_PREEMPTION = 0x1C,
    EVENT_BT_MULTI_CONN_PREEMPTION = 0x1D,
    EVENT_BT_MULTI_CONN_MOB_CALL_ACTION = 0x1E,
    EVENT_BT_MULTI_CONN_PROFS_PULL_BACK = 0x1F,
    EVENT_BT_MULTI_CONN_DISC_PROFS = 0x20,
    EVENT_BT_MULTI_CONN_SET_DEVICE_STATE = 0x21,
    EVENT_BT_FULL_SCENE_CONN = 0x22,
    EVENT_BT_KPI_FIRST_RECONNECT_MOBILE_TIME = 0x23,
    EVENT_BT_KPI_SECOND_RECONNECT_MOBILE_TIME = 0x24,
    EVENT_BT_KPI_MULT_CONN_WORK_MODE_2 = 0x25,
    EVENT_BT_KPI_MULT_CONN_WORK_MODE_1 = 0x26,
    EVENT_BT_KPI_MULT_CONN_WORK_MODE_0 = 0x27,
    EVENT_BT_KPI_VIRTUAL_AUTO_PREEPTEDL_FAILED = 0x28,
    EVENT_BT_KPI_CONNECT_INFO2_END
} event_bt_kpi_connect_info2_t;

typedef enum {
    EVENT_BT_KPI_MEDIA_HANDOVER = 0x01,
    EVENT_BT_KPI_CALL_HANDOVER = 0x02,
    EVENT_BT_KPI_IDLE_HANDOVER = 0x03,
    EVENT_BT_KPI_MEDIA_HO_TIME = 0x04,
    EVENT_BT_KPI_CALL_HO_TIME = 0x05,
    EVENT_BT_KPI_IDLE_HO_TIME = 0x06,
    EVENT_BT_KPI_BATTERY_HANDOVER = 0x07,
    EVENT_BT_KPI_HANDOVER_INFO2_END
} event_bt_kpi_handover_info2_t;

typedef enum {
    EVENT_BT_KPI_A2DP_SNIFF = 0x01,
    EVENT_BT_KPI_HFP_SNIFF = 0x02,
    EVENT_BT_KPI_FOTA = 0x03,
    EVENT_BT_KPI_VID = 0x04,
    EVENT_BT_KPI_A2DP_JITWS_TIME = 0x05,
    EVENT_BT_KPI_HFP_JITWS_TIME = 0x06,
    EVENT_BT_KPI_A2DP_JITWS = 0x07,
    EVENT_BT_KPI_HFP_JITWS = 0x08,
    EVENT_BT_KPI_HDAP_PROC = 0x09,
    EVENT_BT_KPI_PROFILE_INFO2_END
} event_bt_kpi_profile_info2_t;

typedef enum {
    EVENT_BT_KQI_MEDIA_PER = 0x01,
    EVENT_BT_KQI_MEDIA_RSSI = 0x02,
    EVENT_BT_KQI_MEDIA_TXPOWER = 0x03,
    EVENT_BT_KQI_CALL_PER = 0x04,
    EVENT_BT_KQI_CALL_RSSI = 0x05,
    EVENT_BT_KQI_CALL_TXPOWER = 0x06,
    EVENT_BT_KQI_TRANSPORT_INFO2_END
} event_bt_kqi_transport_info2_t;

typedef enum {
    EVENT_BT_KQI_AUDIO_QUALITY_UNDERFLOW = 0x01,
    EVENT_BT_KQI_AUDIO_QUALITY_OVERFLOW = 0x02,
    EVENT_BT_KQI_AUDIO_QUALITY_INFO2_END
} event_bt_kqi_audio_quality_info2_t;

typedef enum {
    EVENT_BTC_DTC_CAIL = 0x00,
    EVENT_BTC_MODE_SEN_CAIL = 0x01,
    EVENT_BTC_PULLING_CALI = 0x02,
    EVENT_BTC_RXDC_CALI = 0x03,
    EVENT_BTC_SATDET_CALI = 0x04,
    EVENT_BTC_TXPWR_CALI = 0x05,
    EVENT_BTC_RXIQ_CALI = 0x06,
    EVENT_BTC_RXLPF_CALI = 0x07,
    EVENT_BTC_DYC_DC_CALI = 0x08,
    EVENT_BT_CALI_INFO2_END
} event_bt_cali_info2_t;

typedef enum {
    EVENT_BTC_TEMP_FLAG = 0xff,
    EVENT_BTC_TEMP_RSSI_INFO_INFO2_END
} event_btc_temp_rssi_info_info2_t;

typedef enum {
    EVENT_BTC_ERROR_BT_INT_ISR = 0x01,
    EVENT_BTC_ERROR_BLE_INT_ISR = 0x02,
    EVENT_BTC_ERROR_MEMCPY = 0x03,
    EVENT_BTC_ERROR_INFO2_END
} event_btc_error_info2_t;

typedef enum {
    EVENT_SWITCH_ON_KEY = 0x01,
    EVENT_SWITCH_ON_START_CHARGER = 0x02,
    EVENT_SWITCH_ON_LOW_INSERT_CHARGE = 0x03,
    EVENT_SWITCH_ON_LOW = 0x04,
    EVENT_SWITCH_ON_RESTART = 0x05,
    EVENT_POWER_ON_INFO2_END
} event_power_on_info2_t;

typedef enum {
    EVENT_SWITCH_OFF_KEY = 0x01,
    EVENT_SWITCH_OFF_LOW_POWER = 0x02,
    EVENT_SWITCH_OFF_REMOTE = 0x03,
    EVENT_SWITCH_OFF_SOFT_RESET = 0x04,
    EVENT_SWITCH_OFF_EXCEPTION_RESET = 0x05,
    EVENT_SWITCH_OFF_SHUT_DOWN = 0x06,
    EVENT_SWITCH_OFF_RESTART = 0x07,
    EVENT_POWER_OFF_INFO2_END
} event_power_off_info2_t;

typedef enum {
    EVENT_BATTERY_ID_NUM = 0x01,
    EVENT_BATTERY_ID_INFO2_END
} event_battery_id_info2_t;

typedef enum {
    EVENT_IN_BOX_VOLT = 0x01,
    EVENT_IN_BOX_CHARGE_TEMP = 0x02,
    EVENT_IN_BOX_CAPACITY = 0x03,
    EVENT_MANAGER__INBOX_POWER_INFO2_END
} event_manager__inbox_power_info2_t;

typedef enum {
    EVENT_OUT_BOX_VOLT = 0x01,
    EVENT_OUT_BOX_CHARGE_TEMP = 0x02,
    EVENT_OUT_BOX_CAPACITY = 0x03,
    EVENT_OUT_BOX_VERSION = 0x04,
    EVENT_OUT_BOX_TWS_VERSION = 0x05,
    EVENT_MANAGER__OUTBOX_POWER_INFO2_END
} event_manager__outbox_power_info2_t;

typedef enum {
    EVENT_WS_CALL_START_CAPACITY = 0x01,
    EVENT_WS_CALL_END_CAPACITY = 0x02,
    EVENT_WS_CALL_END_TX_PERIOD = 0x03,
    EVENT_WS_CALL_END_RX_PERIOD = 0x04,
    EVENT_MANAGER_CALL_POWER_INFO2_END
} event_manager_call_power_info2_t;

typedef enum {
    EVENT_MUSIC_AAC_START_CAPACITY = 0x01,
    EVENT_MUSIC_AAC_STOP_CAPACITY = 0x02,
    EVENT_MUSIC_MSBC_START_CAPACITY = 0x03,
    EVENT_MUSIC_MSBC_STOP_CAPACITY = 0x04,
    EVENT_MUSIC_SBC_STOP_TX_PERIOD = 0x05,
    EVENT_MUSIC_SBC_STOP_RX_PERIOD = 0x06,
    EVENT_MUSIC_AAC_STOP_TX_PERIOD = 0x07,
    EVENT_MUSIC_AAC_STOP_RX_PERIOD = 0x08,
    EVENT_MANAGER_MUSIC_POWER_INFO2_END
} event_manager_music_power_info2_t;

typedef enum {
    EVENT_HANDOVER_START_CAPACITY = 0x01,
    EVENT_HANDOVER_STOP_CAPACITY = 0x02,
    EVENT_MANAGER__HANDOVER_POWER_INFO2_END
} event_manager__handover_power_info2_t;

typedef enum {
    EVENT_GESTURE_START_CAPACITY = 0x01,
    EVENT_GESTURE_STOP_CAPACITY = 0x02,
    EVENT_GESTURE_START_CPUUSAGE = 0x03,
    EVENT_GESTURE_DURATION_TIME = 0x04,
    EVENT_MANAGER__GESTURE_POWER_INFO2_END
} event_manager__gesture_power_info2_t;

typedef enum {
    EVENT_LOWVOLT_SOC = 0x01,
    EVENT_LOW_VOLT_H = 0x02,
    EVENT_LOW_VOLT_L = 0x03,
    EVENT_POWER_LOW_ALERT_INFO2_END
} event_power_low_alert_info2_t;

typedef enum {
    EVENT_COUL_CHANGE = 0x01,
    EVENT_REALTIME_CURRENT = 0x02,
    EVENT_VOLT_ABNORMAL_H = 0x03,
    EVENT_VOLT_ABNORMAL_L = 0x04,
    EVENT_BATTERY_CHANGE_INFO2_END
} event_battery_change_info2_t;

typedef enum {
    EVENT_TEMP_PROTECT_TEMP_VALUE = 0x01,
    EVENT_TEMP_PROTECT_CAUSE = 0x02,
    EVENT_TEMP_PROTECT_STATUS = 0x03,
    EVENT_TEMP_PROTECT_MANAGER_INFO2_END
} event_temp_protect_manager_info2_t;

typedef enum {
    EVENT_WORKING_DAYS = 0x01,
    EVENT_TOTAL_POWERON_TIME_HIGH = 0x02,
    EVENT_TOTAL_POWERON_TIME_LOW = 0x03,
    EVENT_POWERON_TIMING_INFO2_END
} event_poweron_timing_info2_t;

typedef enum {
    EVENT_CHARGING_MINUTES = 0x01,
    EVENT_TOTAL_CHARGE_TIMES_HIGH = 0x02,
    EVENT_TOTAL_CHARGE_TIMES_LOW = 0x03,
    EVENT_TOTAL_CHARGE_CUTOUT_TIMES_HIGH = 0x04,
    EVENT_TOTAL_CHARGE_CUTOUT_TIMES_LOW = 0x05,
    EVENT_CHARGING_STATISTIC_INFO2_END
} event_charging_statistic_info2_t;

typedef enum {
    EVENT_POWER_ULPM_APP_ENTER_LIGHT_SLEEP = 0x01,
    EVENT_POWER_ULPM_APP_ENTER_DEEP_SLEEP = 0x02,
    EVENT_POWER_ULPM_APP_WORK = 0x03,
    EVENT_POWER_ULPM_BT_ENTER_LIGHT_SLEEP = 0x04,
    EVENT_POWER_ULPM_BT_ENTER_DEEP_SLEEP = 0x05,
    EVENT_POWER_ULPM_BT_WORK = 0x06,
    EVENT_POWER_ULPM_SYS_ENTER_DEEP_SLEEP = 0x07,
    EVENT_POWER_ULPM_SYS_EXIT_DEEP_SLEEP = 0x08,
    EVENT_POWER_ULPM_VETO_IN_BT_BTC = 0x09,
    EVENT_POWER_ULPM_VETO_IN_BT_BTH = 0x0A,
    EVENT_POWER_ULPM_VETO_IN_BT_PLT = 0x0B,
    EVENT_POWER_ULPM_VETO_IN_BT_DSP = 0x0C,
    EVENT_POWER_ULPM_VETO_IN_APP_A2B = 0x0D,
    EVENT_POWER_ULPM_VETO_IN_APP_A2D = 0x0E,
    EVENT_POWER_ULPM_VETO_IN_APP_PLT = 0x0F,
    EVENT_POWER_ULPM_SWITCH_CLK_BT_CURRENT  = 0x10,
    EVENT_POWER_ULPM_SWITCH_CLK_APP_CURRENT = 0x11,
    EVENT_MCU_CPU_LOAD_CURRENT = 0x12,
    EVENT_DSP_CPU_LOAD_CURRENT = 0x13,
    EVENT_POWER_ULPM_SWITCH_CLK_BT_ADJUST = 0x14,
    EVENT_POWER_ULPM_SWITCH_CLK_APP_ADJUST = 0x15,
    EVENT_POWER_ULPM_WFI_BT = 0x16,
    EVENT_POWER_ULPM_WFI_APP = 0x17,
    EVENT_POWER_ULPM_WFI_DSP = 0x18,
    EVENT_POWER_ULPM_ENTER = 0x19,
    EVENT_POWER_ULPM_EXIT = 0x1A,
    EVENT_POWER_ULPM_HIGH_PERF_TOP1_EVENT = 0x1B,
    EVENT_POWER_ULPM_HIGH_PERF_TOP1_TIME = 0x1C,
    EVENT_POWER_ULPM_HIGH_PERF_TOP2_EVENT = 0x1D,
    EVENT_POWER_ULPM_HIGH_PERF_TOP2_TIME = 0x1E,
    EVENT_POWER_ULPM_HIGH_PERF_TOP3_EVENT = 0x1F,
    EVENT_POWER_ULPM_HIGH_PERF_TOP3_TIME = 0x21,
    EVENT_POWER_ULPM_HIGH_PERF_TIMEOUT_EVENT = 0x22,
    EVENT_POWER_ULPM_HIGH_PERF_TIMEOUT_VALUE = 0x23,
    EVENT_POWER_ULPM_INFO2_END
} event_power_ulpm_info2_t;

typedef enum {
    EVENT_POWER_ULPM_BATT_PERCENT = 0x01,
    EVENT_POWER_ULPM_SYS_SLEEP_PERCENT = 0x02,
    EVENT_POWER_ULPM_BT_SLEEP_PERCENT = 0x03,
    EVENT_POWER_ULPM_HIGH_PERF_PERCENT = 0x04,
    EVENT_POWER_ULPM_SYS_WAKEUP_SOURCE_H = 0x05,
    EVENT_POWER_ULPM_SYS_WAKEUP_SOURCE_L = 0x06,
    EVENT_POWER_ULPM_APP_WAKEUP_SOURCE_H = 0x07,
    EVENT_POWER_ULPM_APP_WAKEUP_SOURCE_L = 0x08,
    EVENT_POWER_STATISTICS_INFO2_END
} event_power_statistics_info2_t;

typedef enum {
    EVENT_LONG_PRESS_KEY = 0x01,
    EVENT_SHORT_PRESS_KEY = 0x02,
    EVENT_DOUBLE_CLICK_KEY = 0x04,
    EVENT_TRIPLE_CLICK_KEY = 0x05,
    EVENT_PRESS_KEY_MANAGER_INFO2_END
} event_press_key_manager_info2_t;

typedef enum {
    EVENT_MIC1_MANAGER = 0x01,
    EVENT_MIC2_MANAGER = 0x02,
    EVENT_MIC_MANAGER_INFO2_END
} event_mic_manager_info2_t;

typedef enum {
    EVENT_SPK_START = 0x01,
    EVENT_SPK_STOP = 0x02,
    EVENT_SPK_MANAGER_INFO2_END
} event_spk_manager_info2_t;

typedef enum {
    EVENT_ACC_MANAGER = 0x01,
    EVENT_CAP_MANAGER = 0x02,
    EVENT_PROXIMITY_MANAGER = 0x03,
    EVENT_PROXIMITY_FARAWAY_AVG = 0x04,
    EVENT_PROXIMITY_FARAWAY_NOW = 0x05,
    EVENT_PROXIMITY_NEAR_AVG = 0x06,
    EVENT_PROXIMITY_NEAR_NOW = 0x07,
    EVENT_CAP_FARAWAY_AVG = 0x08,
    EVENT_CAP_FARAWAY_NOW = 0x09,
    EVENT_CAP_NEAR_AVG = 0x0A,
    EVENT_CAP_NEAR_NOW = 0x0B,
    EVENT_SENSOR_MANAGER_INFO2_END
} event_sensor_manager_info2_t;

typedef enum {
    EVENT_CODEC_OPEN = 0x01,
    EVENT_CODEC_CLOSE = 0x02,
    EVENT_AUDIO_TYPE = 0x03,
    EVENT_AUDIO_TOTAL_TIME = 0x04,
    EVENT_AUDIO_TOTAL_PACKET_H = 0x05,
    EVENT_AUDIO_TOTAL_PACKET_L = 0x06,
    EVENT_AUDIO_OVER_FLOW_H = 0x07,
    EVENT_AUDIO_OVER_FLOW_L = 0x08,
    EVENT_AUDIO_UNDER_FLOW_H = 0x09,
    EVENT_AUDIO_UNDER_FLOW_L = 0x0A,
    EVENT_AUDIO_PACKET_LOSS_H = 0x0B,
    EVENT_AUDIO_PACKET_LOSS_L = 0x0C,
    EVENT_AUDIO_PERFORMANCE_ERROR_H = 0x0D,
    EVENT_AUDIO_PERFORMANCE_ERROR_L = 0x0E,
    EVENT_AUDIO_CODEC_CONTROL_FAILURE = 0x20,
    EVENT_AUDIO_UNCONTINUOUS_OVER_FLOW_H = 0x21,
    EVENT_AUDIO_UNCONTINUOUS_OVER_FLOW_L = 0x22,
    EVENT_AUDIO_UNCONTINUOUS_UNDER_FLOW_H = 0x23,
    EVENT_AUDIO_UNCONTINUOUS_UNDER_FLOW_L = 0x24,
    EVENT_AUDIO_UNCONTINUOUS_PACKET_LOSS_H = 0x25,
    EVENT_AUDIO_UNCONTINUOUS_PACKET_LOSS_L = 0x26,
    EVENT_AUDIO_DEVICE_STATUS = 0x30,
    EVENT_CODEC_MANAGER_INFO2_END
} event_codec_manager_info2_t;

typedef enum {
    EVENT_DSP_POWER_ON = 0x01,
    EVENT_DSP_POWER_OFF = 0x02,
    EVENT_AUDIO_ERROR_TYPE = 0x03,
    EVENT_AUDIO_ERROR_TIME_H = 0x04,
    EVENT_AUDIO_ERROR_TIME_L = 0x05,
    EVENT_AUDIO_ERROR_TIME_TO_END_H = 0x06,
    EVENT_AUDIO_ERROR_TIME_TO_END_L = 0x07,
    EVENT_AUDIO_ERROR_CODE_TYPE = 0x08,
    EVENT_AUDIO_ERROR_CODE_VALUE = 0x09,
    EVENT_AUDIO_DELAY_TIMES_H = 0x10,
    EVENT_AUDIO_DELAY_TIMES_L = 0x11,
    EVENT_AUDIO_UNSYNC_HIGH_TIMES_H = 0x12,
    EVENT_AUDIO_UNSYNC_HIGH_TIMES_L = 0x13,
    EVENT_AUDIO_UNSYNC_MID_TIMES_H = 0x14,
    EVENT_AUDIO_UNSYNC_MID_TIMES_L = 0x15,
    EVENT_AUDIO_UNSYNC_LOW_TIMES_H = 0x16,
    EVENT_AUDIO_UNSYNC_LOW_TIMES_L = 0x17,
    EVENT_DSP_MANAGER_INFO2_END
} event_dsp_manager_info2_t;

typedef enum {
    EVENT_WS_CALL_IN_TYPE_COMMON = 0x01,
    EVENT_WS_CALL_IN_TYPE_REMOTE = 0x03,
    EVENT_WS_CALL_INCOMING_INFO2_END
} event_ws_call_incoming_info2_t;

typedef enum {
    EVENT_WS_CALL_OUT_TYPE_COMMON = 0x01,
    EVENT_WS_CALL_OUT_TYPE_SOS = 0x02,
    EVENT_WS_CALL_OUT_TYPE_REMOTE = 0x03,
    EVENT_WS_CALL_DIAL_INFO2_END
} event_ws_call_dial_info2_t;

typedef enum {
    EVENT_WS_CALL_END_COMMON = 0x00,
    EVENT_WS_CALL_END_NO_SERVICE = 0x01,
    EVENT_WS_CALL_END_INCOM_REJ = 0x02,
    EVENT_WS_CALL_END_NETWORK_END = 0x03,
    EVENT_WS_CALL_END_OTHER_CAUSE = 0x04,
    EVENT_WS_CALL_END_INFO2_END
} event_ws_call_end_info2_t;

typedef enum {
    EVENT_MUSIC_STOP = 0x01,
    EVENT_MUSIC_PLAY = 0x02,
    EVENT_MUSIC_PREVIOUS = 0x03,
    EVENT_MUSIC_NEXT = 0x04,
    EVENT_MUSIC_DOUBLE_KICK_FUNC = 0x05,
    EVENT_MUSIC_MANAGER_CONTROL_INFO2_END
} event_music_manager_control_info2_t;

typedef enum {
    EVENT_FOREGROUND_UPGRADE = 0x01,
    EVENT_SILENT_UPGRADE = 0x02,
    EVENT_UPGRADE_START_INFO2_END
} event_upgrade_start_info2_t;

typedef enum {
    EVENT_UPGRADE_TYPE_USB = 0x01,
    EVENT_UPGRADE_TYPE_OTA = 0x03,
    EVENT_UPGRADE_TYPE_INFO2_END
} event_upgrade_type_info2_t;

typedef enum {
    EVENT_UPGRADE_FAIL_DATATRANS = 0x01,
    EVENT_UPGRADE_FAIL_DATACHECK = 0x02,
    EVENT_UPGRADE_FAIL_DATAWRITE = 0x03,
    EVENT_UPGRADE_FAIL_DATAILLEGAL = 0x04,
    EVENT_UPGRADE_FAIL_NOT_IN_BOX = 0x05,
    EVENT_UPGRADE_FAIL_TWS_DISCONNECTED = 0x06,
    EVENT_UPGRADE_FAIL_HIGH_LOSS = 0x07,
    EVENT_UPGRADE_FAIL_DOWNLOAD_TIMEOUT = 0x08,
    EVENT_UPGRADE_FAIL_HEADER_PARSE_ERROR = 0x09,
    EVENT_UPGRADE_FAIL_BOX_MOVE_CHECK_FAIL = 0x10,
    EVENT_UPGRADE_FAIL_AUDIO_RES_MOVE_CHECK_FAIL = 0x11,
    EVENT_UPGRADE_FAIL_REPORT_VALID_TIMEOUT = 0x12,
    EVENT_UPGRADE_FAIL_CREATE_TIMER = 0x13,
    EVENT_UPGRADE_FAIL_BOX_CLOSED = 0x14,
    EVENT_UPGRADE_FAIL_INFO2_END
} event_upgrade_fail_info2_t;

typedef enum {
    EVENT_UPGRADE_END_FORE_SUCC = 0x01,
    EVENT_UPGRADE_END_BACK_SUCC = 0x02,
    EVENT_UPGRADE_END_FORE_FAIL = 0x03,
    EVENT_UPGRADE_END_BACK_FAIL = 0x04,
    EVENT_UPGRADE_END_INFO2_END
} event_upgrade_end_info2_t;

typedef enum {
    EVENT_UPGRADE_TRANS_START = 0x01,
    EVENT_UPGRADE_TRANS_END = 0x02,
    EVENT_UPGRADE_TRANS_INFO2_END
} event_upgrade_trans_info2_t;

typedef enum {
    EVENT_UPGRADE_SELECT = 0x01,
    EVENT_UPGRADE_CANCEL = 0x02,
    EVENT_UPGRADE_CONFIRM_INFO_END = 0x03,
    EVENT_UPGRADE_CONFIRM_INFO2_END
} event_upgrade_confirm_info2_t;

typedef enum {
    EVENT_LOG_MCU_DEBUG_FULL = 0x01,
    EVENT_LOG_BT_DEBUG_FULL = 0x02,
    EVENT_LOG_USER_EVENT_FULL = 0x03,
    EVENT_LOG_MCU_DUMP_FULL = 0x04,
    EVENT_LOG_BT_DUMP_FULL = 0x05,
    EVENT_LOG_ERRORCODE_FULL = 0x06,
    EVENT_LOG_OTA_UPGRADE_START = 0x07,
    EVENT_LOG_OTA_UPGRADE_TYPE_USB = 0x08,
    EVENT_LOG_OTA_UPGRADE_TYPE_OTA = 0x09,
    EVENT_LOG_OTA_UPGRADE_FAIL = 0x0A,
    EVENT_LOG_OTA_UPGRADE_END = 0x0B,
    EVENT_LOG_OTA_UPGRADE_TRANS = 0x0C,
    EVENT_LOG_OTA_UPGRADE_CONFIRM = 0x0D,
    EVENT_LOG_OTA_UPGRADE_VERSION = 0x0E,
    EVENT_LOG_OTA_UPGRADE_VERSION_CURRENT = 0x0F,
    EVENT_LOG_MCU_BT_CONTENT_RECORD_FULL_INFO2_END
} event_log_mcu_bt_content_record_full_info2_t;

typedef enum {
    EVENT_LOG_MCU_LOG_REACH_UPLOAD_CONDNTION = 0x01,
    EVENT_LOG_MCU_HAPPEN_DUMP = 0x02,
    EVENT_LOG_NOTIFY_APP_FETCH_CONTENT_INFO2_END
} event_log_notify_app_fetch_content_info2_t;

typedef enum {
    EVENT_LOG_UPDATE_TRANS_START = 0x01,
    EVENT_LOG_UPDATE_TRANS_END = 0x02,
    EVENT_LOG_UPDATE_TRANS_INFO2_END
} event_log_update_trans_info2_t;

typedef enum {
    EVENT_LOG_KERNEL_MEMORY_POOL_MONITOR = 0x01,
    EVENT_COMPONENT_MEMORY_POOL_MONITOR = 0x02,
    EVENT_LOG_MEMORY_POOL_MAX_USED_VALUE_MONITOR_INFO2_END
} event_log_memory_pool_max_used_value_monitor_info2_t;

typedef enum {
    EVENT_BOX_OPEN = 0x01,
    EVENT_BOX_CLOSE = 0x02,
    EVENT_BOX_WIRELESS_TEMP_ON_TX = 0x03,
    EVENT_BOX_WIRELESS_TEMP_OUT_TX = 0x04,
    EVENT_BOX_WIRELESS_STOP_CHG_FIRST = 0x05,
    EVENT_BOX_WIRELESS_STOP_CHG_SECOND = 0x06,
    EVENT_BOX_WIRELESS_STOP_CHG_THIRD = 0x07,
    EVENT_BOX_OPEN_REQ = 0x08,
    EVENT_BOX_OPEN_STATUS = 0x09,
    EVENT_BOX_CLOSE_REQ = 0x0A,
    EVENT_BOX_CLOSE_STATUS = 0x0B,
    EVENT_REISSUE_BOX_OPEN_OR_CLOSE = 0x0C,
    EVENT_BOX_TOUCH_2S_STATUS = 0x0D,
    EVENT_BOX_OPEN_CLOSE_INFO2_END
} event_box_open_close_info2_t;

typedef enum {
    EVENT_BOX_LEFT_IN = 0x01,
    EVENT_BOX_LEFT_OUT = 0x02,
    EVENT_BOX_RIGHT_IN = 0x03,
    EVENT_BOX_RIGHT_OUT = 0x04,
    EVENT_BOX_LEFT_IN_COVER_CLOSED = 0x05,
    EVENT_BOX_LEFT_OUT_COVER_CLOSED = 0x06,
    EVENT_BOX_RIGHT_IN_COVER_CLOSED = 0x07,
    EVENT_BOX_RIGHT_OUT_COVER_CLOSED = 0x08,
    EVENT_BOX_OUT_TIME = 0x09,
    EVENT_BOX_IN_TIME = 0x0A,
    EVENT_BOX_TWS_IN_OUT_INFO2_END
} event_box_tws_in_out_info2_t;

typedef enum {
    EVENT_BOX_LONG_PRESS_KEY = 0x01,
    EVENT_BOX_SHORT_PRESS_KEY = 0x02,
    EVENT_BOX_DOUBLE_CLICK_KEY = 0x03,
    EVENT_BOX_TRIPLE_CLICK_KEY = 0x04,
    EVENT_BOX_KEY_INFO2_END
} event_box_key_info2_t;

typedef enum {
    EVENT_BOX_CHARGE_LEFT_START = 0x01,
    EVENT_BOX_CHARGE_LEFT_END = 0x02,
    EVENT_BOX_CHARGE_LEFT_FULL = 0x03,
    EVENT_BOX_CHARGE_RIGHT_START = 0x04,
    EVENT_BOX_CHARGE_RIGHT_END = 0x05,
    EVENT_BOX_CHARGE_RIGHT_FULL = 0x06,
    EVENT_BOX_CHARGE_MANAGER_INFO2_END
} event_box_charge_manager_info2_t;

typedef enum {
    EVENT_BOX_CHARGE_START = 0x01,
    EVENT_BOX_CHARGE_END = 0x02,
    EVENT_BOX_CHARGE_FULL = 0x03,
    EVENT_BOX_CHARGER_MANAGER_INFO2_END
} event_box_charger_manager_info2_t;

typedef enum {
    EVENT_AUDIO_ANC_START = 0x01,
    EVENT_AUDIO_ANC_END = 0x02,
    EVENT_AUDIO_ANC_MANAGER_INFO2_END
} event_audio_anc_manager_info2_t;

typedef enum {
    EVENT_AUDIO_VOICE_WAKEUP_START = 0x01,
    EVENT_AUDIO_VOICE_WAKEUP_END = 0x02,
    EVENT_AUDIO_VOICE_WAKEUP_MANAGER_INFO2_END
} event_audio_voice_wakeup_manager_info2_t;

typedef enum {
    EVENT_AUDIO_VOICE_ID_START = 0x01,
    EVENT_AUDIO_VOICE_ID_END = 0x02,
    EVENT_AUDIO_VOICE_ID_INFO2_END
} event_audio_voice_id_info2_t;

typedef enum {
    EVENT_POWER_ABNORMAL_SOC = 0x01,
    EVENT_POWER_ABNORMAL_VOLTAGE = 0x02,
    EVENT_POWER_ABNORMAL_TEMPERATURE = 0x03,
    EVENT_POWER_ABNORMAL_CYCLE = 0x04,
    EVENT_POWER_ABNORMAL_CHARGE_TIMEOUT = 0x05,
    EVENT_POWER_ABNORMAL_POWER_NOT_IN_TIME = 0x06,
    EVENT_POWER_ABNORMAL_FALL = 0x07,
    EVENT_POWER_ABNORMAL_MISMATCHING = 0x08,
    EVENT_POWER_ABNORMAL_INFO2_END
} event_power_abnormal_info2_t;

typedef enum {
    EVENT_BT_KQI_MONO_HDAP = 0x01,
    EVENT_BT_KQI_DUAL_HDAP = 0x02,
    EVENT_BT_KQI_HD_VOICE = 0x03,
    EVENT_BT_KQI_HD_MUSIC = 0x04,
    EVENT_BT_KQI_HD_INFO2_END
} event_bt_kqi_hd_info2_t;

typedef enum {
    EVENT_BT_PDL_NUM = 0x01,
    EVENT_BT_CLASS_AND_MF_OF_RD = 0x02,
    EVENT_BT_REMOTE_DEVICE_INFO2_END
} event_bt_remote_device_info2_t;

/* forth-level:Info3 */
typedef enum {
    EVENT_BT_UX_OPEN_BOX = 0x01,
    EVENT_BT_UX_CLOSE_BOX = 0x02,
    EVENT_BT_UX_OUT_BOX = 0x03,
    EVENT_BT_UX_IN_BOX = 0x04,
    EVENT_BT_UX_BOX_INFO3_END
} event_bt_ux_box_info3_t;

typedef enum {
    EVENT_BT_UX_MANDATORY_PAIR = 0x01,
    EVENT_BT_UX_FACTORY_RESTORE = 0x02,
    EVENT_BT_UX_ENTER_FREEMAN = 0x03,
    EVENT_BT_UX_KEYPRESS_INFO3_END
} event_bt_ux_keypress_info3_t;

typedef enum {
    EVENT_BT_UX_NEARBY_NFC = 0x01,
    EVENT_BT_UX_NEARBY_INFO3_END
} event_bt_ux_nearby_info3_t;

typedef enum {
    EVENT_BT_UX_OUT_EAR = 0x01,
    EVENT_BT_UX_IN_EAR = 0x02,
    EVENT_BT_UX_WEAR_INFO3_END
} event_bt_ux_wear_info3_t;

typedef enum {
    EVENT_BT_UX_CALL_ANSWER = 0x01,
    EVENT_BT_UX_CALL_HANGUP = 0x02,
    EVENT_BT_UX_CALL_REJECT = 0x03,
    EVENT_BT_UX_CALL_INFO3_END
} event_bt_ux_call_info3_t;

typedef enum {
    EVENT_BT_UX_MEDIA_PLAY = 0x01,
    EVENT_BT_UX_MEDIA_PAUSE = 0x02,
    EVENT_BT_UX_MEDIA_STOP = 0x03,
    EVENT_BT_UX_MEDIA_FORWARD = 0x04,
    EVENT_BT_UX_MEDIA_BACKWARD = 0x05,
    EVENT_BT_UX_MEDIA_INFO3_END
} event_bt_ux_media_info3_t;

typedef enum {
    EVENT_BT_UX_MEDIA_VOLUME_UP = 0x01,
    EVENT_BT_UX_MEDIA_VOLUME_DOWN = 0x02,
    EVENT_BT_UX_VOICE_VOLUME_UP = 0x03,
    EVENT_BT_UX_VOICE_VOLUME_DOWN = 0x04,
    EVENT_BT_UX_VOLUME_INFO3_END
} event_bt_ux_volume_info3_t;

typedef enum {
    EVENT_BT_UX_OPEN_VR = 0x01,
    EVENT_BT_UX_CLOSE_VR = 0x02,
    EVENT_BT_UX_DENOISE = 0x03,
    EVENT_BT_UX_HEARTHROUGH = 0x04,
    EVENT_BT_UX_AUDIO_INFO3_END
} event_bt_ux_audio_info3_t;

typedef enum {
    EVENT_BT_UX_SENSOR_CLICK = 0x01,
    EVENT_BT_UX_OPEN_BT = 0x02,
    EVENT_BT_UX_PROHIBIT_CLOSE_BT = 0x03,
    EVENT_BT_UX_ALLOWED_CLOSE_BT = 0x04,
    EVENT_BT_UX_PROHIBIT_HANDOVER = 0x05,
    EVENT_BT_UX_ALLOWED_HANDOVER = 0x06,
    EVENT_BT_UX_SERVICE_CTRL_INFO3_END
} event_bt_ux_service_ctrl_info3_t;

typedef enum {
    EVENT_BT_UX_LEFT_OUT_BOX = 0x01,
    EVENT_BT_UX_RIGTH_OUT_BOX = 0x02,
    EVENT_BT_UX_LEFT_IN_BOX = 0x03,
    EVENT_BT_UX_RIGTH_IN_BOX = 0x04,
    EVENT_BT_UX_LEFT_USE_BGN = 0x05,
    EVENT_BT_UX_RIGHT_USE_BGN = 0x06,
    EVENT_BT_UX_EARBUDS_CUSTOM_INFO3_END
} event_bt_ux_earbuds_custom_info3_t;

typedef enum {
    EVENT_BT_UX_DEVICE_NAME_SIZE_ONE = 0x01,
    EVENT_BT_UX_DEVICE_NAME_SIZE_TWO = 0x02,
    EVENT_BT_UX_DEVICE_NAME_SIZE_THREE = 0x03,
    EVENT_BT_UX_DEVICE_NAME_SIZE_OTHER = 0x04,
    EVENT_BT_UX_CHANGE_DEVICE_NAME = 0x05,
    EVENT_BT_UX_COMMON_INFO3_END
} event_bt_ux_common_info3_t;

typedef enum {
    EVENT_BT_TWS_NATURE_LEFT = 0x01,
    EVENT_BT_TWS_NATURE_RIGHT = 0x02,
    EVENT_BT_TWS_NATURE_INFO3_END
} event_bt_tws_nature_info3_t;

typedef enum {
    EVENT_BT_TWS_ROLE_MASTER = 0x01,
    EVENT_BT_TWS_ROLE_SLAVE = 0x02,
    EVENT_BT_TWS_ROLE_FREEMAN = 0x03,
    EVENT_BT_TWS_ROLE_INFO3_END
} event_bt_tws_role_info3_t;

typedef enum {
    EVENT_BT_NV_READ_DEVICE_ADDR_SUCCESS = 0x01,
    EVENT_BT_NV_READ_EARBUD_NATURE_SUCCESS = 0x02,
    EVENT_BT_NV_READ_DEVICE_NAME_SUCCESS = 0x03,
    EVENT_BT_NV_READ_EARBUD_PDL_SUCCESS = 0x04,
    EVENT_BT_NV_READ_MODEL_PDL_SUCCESS = 0x05,
    EVENT_BT_NV_READ_MOBILE_PDL_ORDER_SUCCESS = 0x06,
    EVENT_BT_NV_READ_PEER_ADDR_SUCCESS = 0x07,
    EVENT_BT_NV_READ_CLOUD_TOKEN_SUCCESS = 0x08,
    EVENT_BT_NV_READ_LOG_LEVEL_SUCCESS = 0x09,
    EVENT_BT_NV_READ_RSSI_SUCCESS = 0x0A,
    EVENT_BT_NV_READ_MODEL_ID_SUCCESS = 0x0B,
    EVENT_BT_NV_READ_SN_SUCCESS = 0x0C,
    EVENT_BT_NV_READ_ALL_NV_DATA_SUCCESS = 0x0D,
    EVENT_BT_NV_READ_INFO3_END
} event_bt_nv_read_info3_t;

typedef enum {
    EVENT_BT_NV_WRITE_EARBUD_PDL_SUCCESS = 0x01,
    EVENT_BT_NV_WRITE_SINGLE_MOBILE_PDL_SUCCESS = 0x02,
    EVENT_BT_NV_WRITE_MULI_MOBILE_PDL_SUCCESS = 0x03,
    EVENT_BT_NV_WRITE_MOBILE_PDL_ORDER_SUCCESS = 0x04,
    EVENT_BT_NV_WRITE_CLOUD_TOKEN_SUCCESS = 0x05,
    EVENT_BT_NV_WRITE_LOG_LEVEL_SUCCESS = 0x06,
    EVENT_BT_NV_WRITE_INFO3_END
} event_bt_nv_write_info3_t;

typedef enum {
    EVENT_BT_TWS_MODE_SNIFF = 0x01,
    EVENT_BT_TWS_MODE_SOCTWS = 0x02,
    EVENT_BT_UM_TWS_MODE_INFO3_END
} event_bt_um_tws_mode_info3_t;

typedef enum {
    EVENT_BT_CONNECT_BREDR = 0x01,
    EVENT_BT_CONNECT_BLE = 0x02,
    EVENT_BT_UM_CONNECT_MODE_INFO3_END
} event_bt_um_connect_mode_info3_t;

typedef enum {
    EVENT_BT_CONNECT_NORMAL_PAIR = 0x01,
    EVENT_BT_CONNECT_CLOUD_PAIR = 0x02,
    EVENT_BT_CONNECT_MOBILE_PREEMP = 0x03,
    EVENT_BT_CONNECT_TRUST_LOOP = 0x04,
    EVENT_BT_UM_CONNECT_METHOD_INFO3_END
} event_bt_um_connect_method_info3_t;

typedef enum {
    EVENT_BT_UM_UNICAST_PROFILE_A2DP = 0x01,
    EVENT_BT_UM_UNICAST_PROFILE_HFP = 0x02,
    EVENT_BT_UM_UNICAST_PROFILE_INFO3_END
} event_bt_um_unicast_profile_info3_t;

typedef enum {
    EVENT_BT_UM_UNICAST_SCENE_DEFAULT = 0x01,
    EVENT_BT_UM_UNICAST_SCENE_GAME = 0x02,
    EVENT_BT_UM_UNICAST_SCENE_MUSIC = 0x03,
    EVENT_BT_UM_UNICAST_SCENE_VEDIO = 0x04,
    EVENT_BT_UM_UNICAST_SCENE_CALL = 0x05,
    EVENT_BT_UM_UNICAST_SCENE_INFO3_END
} event_bt_um_unicast_scene_info3_t;

typedef enum {
    EVENT_BT_DISCOVERY_BGN = 0x01,
    EVENT_BT_DISCOVERY_END = 0x02,
    EVENT_BT_DISCOVERY_CANCEL_BGN = 0x03,
    EVENT_BT_DISCOVERY_CANCEL_END = 0x04,
    EVENT_BT_KPI_NEARBY_INFO3_END
} event_bt_kpi_nearby_info3_t;

typedef enum {
    EVENT_BT_ONLY_PAGE_SCAN_BGN = 0x01,
    EVENT_BT_ONLY_PAGE_SCAN_END = 0x02,
    EVENT_BT_NO_PAGE_SCAN_BGN = 0x03,
    EVENT_BT_NO_PAGE_SCAN__END = 0x04,
    EVENT_BT_KPI_PAGE_SCAN_INFO3_END
} event_bt_kpi_page_scan_info3_t;

typedef enum {
    EVENT_BT_MOBILE_CONNECT_BGN = 0x01,
    EVENT_BT_MOBILE_CONNECT_END = 0x02,
    EVENT_BT_MOBILE_CONNECT_ACL_END = 0x03,
    EVENT_BT_KPI_MOBILE_CONNECT_INFO3_END
} event_bt_kpi_mobile_connect_info3_t;

typedef enum {
    EVENT_BT_TWS_CONNECT_BGN = 0x01,
    EVENT_BT_TWS_CONNECT_END = 0x02,
    EVENT_BT_TWS_OPEN_BOX_WITH_COUPLE_CONNECT_BGN = 0x03,
    EVENT_BT_TWS_OPEN_BOX_WITH_COUPLE_CONNECT_END = 0x04,
    EVENT_BT_KPI_TWS_CONNECT_INFO3_END
} event_bt_kpi_tws_connect_info3_t;

typedef enum {
    EVENT_BT_MOBILE_PAIRING_BGN = 0x01,
    EVENT_BT_KPI_MOBILE_PAIR_INFO3_END
} event_bt_kpi_mobile_pair_info3_t;

typedef enum {
    EVENT_BT_KPI_RECONNECT_BGN = 0x01,
    EVENT_BT_KPI_RECONNECT_END = 0x02,
    EVENT_BT_KPI_RECONNECT_INFO3_END
} event_bt_kpi_reconnect_info3_t;

typedef enum {
    EVENT_BT_KPI_OPENBOX_RECONNECT_BGN = 0x01,
    EVENT_BT_KPI_OPENBOX_RECONNECT_END = 0x02,
    EVENT_BT_KPI_OPENBOX_RECONNECT_INFO3_END
} event_bt_kpi_openbox_reconnect_info3_t;

typedef enum {
    EVENT_BT_EXPT_MASTER_RECONNECT_BGN = 0x01,
    EVENT_BT_EXPT_MASTER_RECONNECT_END = 0x02,
    EVENT_BT_EXPT_SLAVE_RECONNECT_BGN = 0x03,
    EVENT_BT_EXPT_SLAVE_RECONNECT_END = 0x04,
    EVENT_BT_KPI_TWS_RECONNECT_INFO3_END
} event_bt_kpi_tws_reconnect_info3_t;

typedef enum {
    EVENT_EAR_ABORT_CONN_CONNECTION_PREEMPTION = 0x01,
    EVENT_EAR_ABORT_CONN_FORCE_PAIRING = 0x02,
    EVENT_BT_KPI_EAR_ABORT_CONNECTING_INFO3_END
} event_bt_kpi_ear_abort_connecting_info3_t;

typedef enum {
    EVENT_BT_A2DP_MOB_DISCON_CONNECTION_PREEMPTION = 0x01,
    EVENT_BT_HFP_MOB_DISCON_CONNECTION_PREEMPTION = 0x02,
    EVENT_BT_IDLE_MOB_DISCON_CONNECTION_PREEMPTION = 0x03,
    EVENT_BT_KPI_MOB_DISCON_CONNECTION_PREEMPTION_INFO3_END
} event_bt_kpi_mob_discon_connection_preemption_info3_t;

typedef enum {
    EVENT_BT_MULTI_CONN_MOB_CALL_PULL_BACK = 0x01,
    EVENT_BT_MULTI_CONN_MOB_CALL_PREEMPTION = 0x02,
    EVENT_BT_MULTI_CONN_MOB_CALL_ACTION_INFO3_END
} event_bt_multi_conn_mob_call_action_info3_t;

typedef enum {
    EVENT_BT_MULTI_CONN_PROFS_A2DP_PULL_BACK = 0x01,
    EVENT_BT_MULTI_CONN_PROFS_PULL_BACK_INFO3_END
} event_bt_multi_conn_profs_pull_back_info3_t;

typedef enum {
    EVENT_BT_MULTI_CONN_DISC_PROFS_A2DP = 0x01,
    EVENT_BT_MULTI_CONN_DISC_PROFS_INFO3_END
} event_bt_multi_conn_disc_profs_info3_t;

typedef enum {
    EVENT_BT_MULTI_CONN_SET_ACTIVE = 0x01,
    EVENT_BT_MULTI_CONN_SET_DEVICE_STATE_INFO3_END
} event_bt_multi_conn_set_device_state_info3_t;

typedef enum {
    EVENT_BT_MULTI_CONN_BGN = 0x01,
    EVENT_BT_MULTI_CONN_END = 0x02,
    EVENT_BT_USE_ICARRY_BGN = 0x03,
    EVENT_BT_USE_ICARRY_END = 0x04,
    EVENT_BT_FULL_SCENE_CONN_INFO3_END
} event_bt_full_scene_conn_info3_t;

typedef enum {
    EVENT_BT_KPI_WORK_MODE_JITWS = 0x01,
    EVENT_BT_KPI_WORK_MODE_SOCTWS = 0x02,
    EVENT_BT_KPI_WORK_MODE_INFO3_END
} event_bt_kpi_work_mode_info3_t;

typedef enum {
    EVENT_BT_MEDIA_HANDOVER_BGN = 0x01,
    EVENT_BT_MEDIA_HANDOVER_END = 0x02,
    EVENT_BT_KPI_MEDIA_HANDOVER_INFO3_END
} event_bt_kpi_media_handover_info3_t;

typedef enum {
    EVENT_BT_TELEPHONY_HANDOVER_BGN = 0x01,
    EVENT_BT_TELEPHONY_HANDOVER_END = 0x02,
    EVENT_BT_KPI_CALL_HANDOVER_INFO3_END
} event_bt_kpi_call_handover_info3_t;

typedef enum {
    EVENT_BT_IDLE_HANDOVER_BGN = 0x01,
    EVENT_BT_IDLE_HANDOVER_END = 0x02,
    EVENT_BT_KPI_IDLE_HANDOVER_INFO3_END
} event_bt_kpi_idle_handover_info3_t;

typedef enum {
    EVENT_BT_RECV_AVDTP_START = 0x01,
    EVENT_BT_OPEN_DATA_PATH_START = 0x02,
    EVENT_BT_OPEN_DATA_PATH_SUCCESS = 0x03,
    EVENT_BT_RECV_AVDTP_ACCEPT = 0x04,
    EVENT_BT_KPI_A2DP_SNIFF_INFO3_END
} event_bt_kpi_a2dp_sniff_info3_t;

typedef enum {
    EVENT_BT_RECV_SCO_REQUEST = 0x01,
    EVENT_BT_RECV_SCO_CONNECTED = 0x02,
    EVENT_BT_KPI_HFP_SNIFF_INFO3_END
} event_bt_kpi_hfp_sniff_info3_t;

typedef enum {
    EVENT_BT_FOTA_DATA_START = 0x01,
    EVENT_BT_FOTA_DATA_END = 0x02,
    EVENT_BT_KPI_FOTA_INFO3_END
} event_bt_kpi_fota_info3_t;

typedef enum {
    EVENT_BT_VID_DATA_START = 0x01,
    EVENT_BT_VID_DATA_END = 0x02,
    EVENT_BT_KPI_VID_INFO3_END
} event_bt_kpi_vid_info3_t;

typedef enum {
    EVENT_BT_KPI_A2DP_JITWS_START = 0x01,
    EVENT_BT_KPI_A2DP_JITWS_INFO3_END
} event_bt_kpi_a2dp_jitws_info3_t;

typedef enum {
    EVENT_BT_KPI_HFP_JITWS_START = 0x01,
    EVENT_BT_KPI_HFP_JITWS_INFO3_END
} event_bt_kpi_hfp_jitws_info3_t;

typedef enum {
    EVENT_BT_KPI_HDAP_PROC_START = 0x01,
    EVENT_BT_KPI_HDAP_PROC_STOP  = 0x02,
    EVENT_BT_KPI_HDAP_PROC_INFO3_END
} event_bt_kpi_hdap_proc_info3_t;

typedef enum {
    EVENT_SWITCH_OFF_RESTART_BT_RESETREQ = 0x01,
    EVENT_SWITCH_OFF_RESTART_DSP_RESETREQ = 0x02,
    EVENT_SWITCH_OFF_RESTART_APP_RESETREQ = 0x03,
    EVENT_SWITCH_OFF_RESTART_INFO3_END
} event_switch_off_restart_info3_t;

typedef enum {
    EVENT_TEMP_PROTECT_CAUSE1 = 0x01,
    EVENT_TEMP_PROTECT_CAUSE2 = 0x02,
    EVENT_TEMP_PROTECT_CAUSE_INFO3_END
} event_temp_protect_cause_info3_t;

typedef enum {
    EVENT_TEMP_PROTECT_STATUS1 = 0x01,
    EVENT_TEMP_PROTECT_STATUS2 = 0x02,
    EVENT_TEMP_PROTECT_STATUS3 = 0x03,
    EVENT_TEMP_PROTECT_STATUS_INFO3_END
} event_temp_protect_status_info3_t;

typedef enum {
    EVENT_MIC1_START = 0x01,
    EVENT_MIC1_STOP = 0x02,
    EVENT_MIC1_MANAGER_INFO3_END
} event_mic1_manager_info3_t;

typedef enum {
    EVENT_MIC2_START = 0x01,
    EVENT_MIC2_STOP = 0x02,
    EVENT_MIC2_MANAGER_INFO3_END
} event_mic2_manager_info3_t;

typedef enum {
    EVENT_ACC_OPEN = 0x01,
    EVENT_ACC_CLOSE = 0x02,
    EVENT_ACC_SOFT_RESET = 0x03,
    EVENT_ACC_SOFT_RESET_FAIL = 0x04,
    EVENT_ACC_HARD_RESET = 0x05,
    EVENT_ACC_MANAGER_INFO3_END
} event_acc_manager_info3_t;

typedef enum {
    EVENT_CAP_OPEN = 0x01,
    EVENT_CAP_CLOSE = 0x02,
    EVENT_CAP_MANAGER_INFO3_END
} event_cap_manager_info3_t;

typedef enum {
    EVENT_PROXIMITY_OPEN = 0x01,
    EVENT_PROXIMITY_CLOSE = 0x02,
    EVENT_PROXIMITY_MANAGER_INFO3_END
} event_proximity_manager_info3_t;

typedef enum {
    EVENT_MUSIC_MODE_ASSISTANCE = 0x00,
    EVENT_MUSIC_MODE_START_STOP = 0x01,
    EVENT_MUSIC_MODE_ANC = 0x03,
    EVENT_MUSIC_MODE_NEXT = 0x04,
    EVENT_MUSIC_MODE_NULL = 0x0ff,
    EVENT_MUSIC_DOUBLE_KICK_FUNC_INFO3_END
} event_music_double_kick_func_info3_t;

typedef enum {
    EVENT_UPGRADE_TYPE_USB_FULL = 0x01,
    EVENT_UPGRADE_TYPE_USB_DIFF = 0x02,
    EVENT_UPGRADE_TYPE_USB_INFO3_END
} event_upgrade_type_usb_info3_t;

typedef enum {
    EVENT_UPGRADE_TYPE_OTA_FULL = 0x04,
    EVENT_UPGRADE_TYPE_OTA_DIFF = 0x05,
    EVENT_UPGRADE_TYPE_OTA_INFO3_END
} event_upgrade_type_ota_info3_t;

typedef enum {
    EVENT_LOG_OTA_FOREGROUND_UPGRADE = 0x01,
    EVENT_LOG_OTA_SILENT_UPGRADE = 0x02,
    EVENT_LOG_OTA_UPGRADE_START_INFO3_END
} event_log_ota_upgrade_start_info3_t;

typedef enum {
    EVENT_LOG_OTA_UPGRADE_TYPE_USB_FULL = 0x01,
    EVENT_LOG_OTA_UPGRADE_TYPE_USB_DIFF = 0x02,
    EVENT_LOG_OTA_UPGRADE_TYPE_USB_INFO3_END
} event_log_ota_upgrade_type_usb_info3_t;

typedef enum {
    EVENT_LOG_OTA_UPGRADE_TYPE_OTA_FULL = 0x04,
    EVENT_LOG_OTA_UPGRADE_TYPE_OTA_DIFF = 0x05,
    EVENT_LOG_OTA_UPGRADE_TYPE_OTA_INFO3_END
} event_log_ota_upgrade_type_ota_info3_t;

typedef enum {
    EVENT_LOG_OTA_UPGRADE_FAIL_DATATRANS = 0x01,
    EVENT_LOG_OTA_UPGRADE_FAIL_DATACHECK = 0x02,
    EVENT_LOG_OTA_UPGRADE_FAIL_DATAWRITE = 0x03,
    EVENT_LOG_OTA_UPGRADE_FAIL_DATAILLEGAL = 0x04,
    EVENT_LOG_OTA_UPGRADE_FAIL_NOT_IN_BOX = 0x05,
    EVENT_LOG_OTA_UPGRADE_FAIL_TWS_DISCONNECTED = 0x06,
    EVENT_LOG_OTA_UPGRADE_FAIL_HIGH_LOSS = 0x07,
    EVENT_LOG_OTA_UPGRADE_FAIL_DOWNLOAD_TIMEOUT = 0x08,
    EVENT_LOG_OTA_UPGRADE_FAIL_HEADER_PARSE_ERROR = 0x09,
    EVENT_LOG_OTA_UPGRADE_FAIL_BOX_MOVE_CHECK_FAIL = 0x10,
    EVENT_LOG_OTA_UPGRADE_FAIL_AUDIO_RES_MOVE_CHECK_FAIL = 0x11,
    EVENT_LOG_OTA_UPGRADE_FAIL_REPORT_VALID_TIMEOUT = 0x12,
    EVENT_LOG_OTA_UPGRADE_FAIL_CREATE_TIMER = 0x13,
    EVENT_LOG_OTA_UPGRADE_FAIL_BOX_CLOSED = 0x14,
    EVENT_LOG_OTA_UPGRADE_FAIL_INFO3_END
} event_log_ota_upgrade_fail_info3_t;

typedef enum {
    EVENT_LOG_OTA_UPGRADE_END_FORE_SUCC = 0x01,
    EVENT_LOG_OTA_UPGRADE_END_BACK_SUCC = 0x02,
    EVENT_LOG_OTA_UPGRADE_END_FORE_FAIL = 0x03,
    EVENT_LOG_OTA_UPGRADE_END_BACK_FAIL = 0x04,
    EVENT_LOG_OTA_UPGRADE_END_INFO3_END
} event_log_ota_upgrade_end_info3_t;

typedef enum {
    EVENT_LOG_OTA_UPGRADE_TRANS_START = 0x01,
    EVENT_LOG_OTA_UPGRADE_TRANS_END = 0x02,
    EVENT_LOG_OTA_UPGRADE_TRANS_INFO3_END
} event_log_ota_upgrade_trans_info3_t;

typedef enum {
    EVENT_LOG_OTA_UPGRADE_SELECT = 0x01,
    EVENT_LOG_OTA_UPGRADE_CANCEL = 0x02,
    EVENT_LOG_OTA_UPGRADE_CONFIRM_INFO_END = 0x03,
    EVENT_LOG_OTA_UPGRADE_CONFIRM_INFO3_END
} event_log_ota_upgrade_confirm_info3_t;

typedef enum {
    EVENT_BT_KQI_MONO_HDAP_START = 0x01,
    EVENT_BT_KQI_MONO_HDAP_STOP = 0x02,
    EVENT_BT_KQI_MONO_HDAP_INFO3_END
} event_bt_kqi_mono_hdap_info3_t;

typedef enum {
    EVENT_BT_KQI_DUAL_HDAP_START = 0x01,
    EVENT_BT_KQI_DUAL_HDAP_STOP = 0x02,
    EVENT_BT_KQI_DUAL_HDAP_INFO3_END
} event_bt_kqi_dual_hdap_info3_t;

typedef enum {
    EVENT_BT_KQI_JITWS_HD_VOICE_START = 0x01,
    EVENT_BT_KQI_SOCTWS_HD_VOICE_START = 0x02,
    EVENT_BT_KQI_HD_VOICE_INFO3_END
} event_bt_kqi_hd_voice_info3_t;

typedef enum {
    EVENT_BT_KQI_HD_MUSIC_START = 0x01,
    EVENT_BT_KQI_HD_MUSIC_INFO3_END
} event_bt_kqi_hd_music_info3_t;

typedef enum {
    EVENT_BT_RD_MOBILE = 0x01,
    EVENT_BT_RD_APPLE_MOBILE = 0x02,
    EVENT_BT_RD_OTHER_MOBILE = 0x03,
    EVENT_BT_RD_PAD = 0x04,
    EVENT_BT_RD_APPLE_PAD = 0x05,
    EVENT_BT_RD_OTHER_PAD = 0x06,
    EVENT_BT_RD_WRISTWATCH = 0x07,
    EVENT_BT_RD_APPLE_WRISTWATCH = 0x08,
    EVENT_BT_RD_OTHER_WRISTWATCH = 0x09,
    EVENT_BT_RD_SMART_MONITOR = 0x0A,
    EVENT_BT_RD_OTHER_SMART_MONITOR = 0x0B,
    EVENT_BT_RD_OTHER_CLASS = 0x0C,
    EVENT_BT_CLASS_AND_MF_OF_RD_INFO3_END
} event_bt_class_and_mf_of_rd_info3_t;

typedef enum {
    EVENT_BT_WEAR_CHECK_SWITCH_ON = 0x01,
    EVENT_BT_WEAR_CHECK_SWITCH_OFF = 0x02,
    EVENT_BT_WEAR_CHECK_SWITCH_INFO3_END
} event_bt_wear_check_switch_info3_t;

typedef enum {
    EVENT_BT_MULTI_CONN_SWITCH_ON = 0x01,
    EVENT_BT_MULTI_CONN_SWITCH_OFF = 0x02,
    EVENT_BT_MULTI_CONN_SWITCH_INFO3_END
} event_bt_multi_conn_switch_info3_t;

typedef enum {
    EVENT_BT_HD_VOICE_SWITCH_ON = 0x01,
    EVENT_BT_HD_VOICE_SWITCH_OFF = 0x02,
    EVENT_BT_HD_VOICE_SWITCH_INFO3_END
} event_bt_hd_voice_switch_info3_t;

/**
 * @}
 */
#endif /* SOCAUDIO_USER_EVENT_LOG_H */
