set(BOARD_CMAKE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/${LOSCFG_FAMILY}/${LITEOS_PLATFORM}/board.cmake)
if(EXISTS ${BOARD_CMAKE_PATH})
    include(${BOARD_CMAKE_PATH})
endif()

list(APPEND MODULE_INCLUDE_PUB
${CMAKE_CURRENT_SOURCE_DIR}/${LOSCFG_FAMILY}/common
)

list(APPEND LOCAL_SRCS_y
${CMAKE_CURRENT_SOURCE_DIR}/${LOSCFG_FAMILY}/common/los_mem_check.c
)
